---
- name: Install python virtualenv
  package: 
    name: python-virtualenv
    state: present
  when: "inventory_hostname == groups['swarm_manager'][0]"

- name: Create temporary directory to store related files
  tempfile:
    state: directory
    suffix: traefik_venv
  register: traefik_venv
  when: "inventory_hostname == groups['swarm_manager'][0]"

- name: Install pyyaml inside of virtualenv
  pip: 
    name: pyyaml
    version: 5.1.1
    virtualenv: "{{ traefik_venv.path }}"
  when: "inventory_hostname == groups['swarm_manager'][0]"

- name: Install jsondiff inside of virtualenv
  pip: 
    name: jsondiff
    version: 1.1.2
    virtualenv: "{{ traefik_venv.path }}"
  when: "inventory_hostname == groups['swarm_manager'][0]"

- name: Create temporary directory to store related files
  tempfile:
    state: directory
    suffix: traefik
  register: traefik_temp_dir
  when: "inventory_hostname == groups['swarm_manager'][0]"

- name: Create htpassword string
  command: "htpasswd -bn {{ traefik_dashboard_username }} {{ traefik_dashboard_password }}"
  register: traefik_htpasswd_string
  delegate_to: localhost
  when: "inventory_hostname == groups['swarm_manager'][0]"

- name: Interpolate Ansible variables
  template:
    src: docker-compose.yml.j2
    dest: "{{ traefik_temp_dir.path }}/docker-compose.yml"
  when: "inventory_hostname == groups['swarm_manager'][0]"

- name: Prune all elements
  docker_prune:
    containers: yes
    images: yes
    volumes: yes

- name: Deploy Traefik in Swarm
  docker_stack:
    state: present
    name: traefik
    prune: yes
    compose:
      - "{{ traefik_temp_dir.path }}/docker-compose.yml"
  tags:
    - deploy-stack
  when: "inventory_hostname == groups['swarm_manager'][0]"
  vars:
    ansible_python_interpreter: "{{ traefik_venv.path }}/bin/python"

- name: Remove temporary directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ traefik_venv.path }}"
    - "{{ traefik_temp_dir.path }}"
  when: "inventory_hostname == groups['swarm_manager'][0]"